spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://35.209.164.72:8080/realms/mini-project

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://35.209.164.72:8761/eureka/

keycloak:
  realm: mini-project
  endpoint: http://35.209.164.72:8080
  application:
    client-id: auth-service
    client-secret: PJ6eSkNegOWj6T0waot2Jmx0h2eTDPby

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      enabled: true
  zipkin:
    tracing:
      enabled: true
      endpoint: http://35.209.164.72:9411/api/v2/spans
      connect-timeout: 5000
      read-timeout: 10000
      flush-interval: 1000
      batch-size: 10
