spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/mini-project

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  realm: mini-project
  endpoint: http://localhost:8090
  application:
    client-id: auth-service
    client-secret: yvYjkkXdyk81KJDeJ37E4CKeAL69MIAn

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      enabled: true
  zipkin:
    tracing:
      enabled: true
      endpoint: http://localhost:9411/api/v2/spans
      connect-timeout: 5000
      read-timeout: 10000
      flush-interval: 1000
      batch-size: 10
