spring:
  application:
    name: category-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.209.164.72:5433/category_service_db
    username: narin
    password: narin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://35.209.164.72:8080/realms/mini-project

server:
  port: 8083

resilience4j:
  circuitbreaker:
    enabled: true
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 100
        minimum-number-of-calls: 50
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - com.hrd.categoryservice.exception.DataConflictException
    instances:
      category-service:
        base-config: default

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      enabled: true
  zipkin:
    tracing:
      enabled: true
      endpoint: http://35.209.164.72:9411/api/v2/spans
      connect-timeout: 5000
      read-timeout: 10000
      flush-interval: 1000
      batch-size: 10

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://35.209.164.72:8761/eureka/

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

    instance-id: "${spring.application.name}:${server.port}"





